### ISSUE TITLE
Fabric 1.20.1 Crash

### ISSUE THREAD

**Issue by Gamerbolts** [GenerationsMod/Generations-Core#27]
Hello, I saw your mod and wanted to add it to my modpack however it crashed, no crash log was provided but I saw in the log it mentioned your mod. I am using the following versions

Generations Core 2.3.0-Beta
Minecraft Fabric 1.20.1 0.15.6

I did notice a recent post from Jan about a conflict with MCA Reborn I do also have that in my pack their latest version

MCA Reborn 7.5.14

Here is the log https://pastebin.com/MSBRNBXR

Any help is appreciated. Thank you!

**Comment by JT122406** [comment]
This is a different issue I am modifying the curseforge release now to fix

**Comment by Gamerbolts** [comment]
Thank you!

**Comment by JT122406** [comment]
Please Redownload 2.3.0 and try again

**Comment by LaurentCoolen** [comment]
![Capture d'écran 2024-02-20 164816](https://github.com/GenerationsMod/Generations-Core/assets/160633511/efd6f56f-a459-42f7-9961-cae2bd2402ff)
Hello, I launch the game and it gives me this message

**Comment by GuikiPT** [comment]
> Got farther in loading but new crash
> 
> Crashlog [crash-2024-02-20_09.57.34-client.txt](https://github.com/GenerationsMod/Generations-Core/files/14348089/crash-2024-02-20_09.57.34-client.txt)
> 
> Log [latest.log](https://github.com/GenerationsMod/Generations-Core/files/14348090/latest.log)

```log
[09:55:10] [main/WARN]: Warnings were found!
 - Mod 'FullSlabs' (full_slabs) 3.4.0 recommends version 0.16.0 or later of malilib, which is missing!
	 - You should install version 0.16.0 or later of malilib for the optimal experience.
 - Mod 'LambDynamicLights' (lambdynlights) 2.3.2+1.20.1 recommends version 0.19.1 or later of quilt_loader, which is missing!
	 - You should install version 0.19.1 or later of quilt_loader for the optimal experience.
 - Mod 'Scannable' (scannable) 1.7.12+18ccb75 recommends any version of tooltipfix, which is missing!
	 - You should install any version of tooltipfix for the optimal experience.
 - Mod 'SleepWarp' (sleepwarp) 2.2.0_rc1+1.20.1 recommends version 7.0.1 of mod 'Mod Menu' (modmenu), but only the wrong version is present: 7.2.2!
	 - You should install version 7.0.1 of mod 'Mod Menu' (modmenu) for the optimal experience.
 - Mod 'SleepWarp' (sleepwarp) 2.2.0_rc1+1.20.1 recommends version 3.0.1 of yet-another-config-lib, which is missing!
	 - You should install version 3.0.1 of yet-another-config-lib for the optimal experience.
```

Some mods have their dependencies or sidemods missing.

**Comment by Gamerbolts** [comment]
That is really strange because the modpack loaded just fine before. I'll try to get those mods and see if that works

**Comment by Gamerbolts** [comment]
That did not work unfortunately :(

**Comment by Gamerbolts** [comment]
Hi there using the latest version and still crashing here is my new log and crashlog, Some of those mods say "missing" file but it is recommended to have not a requirement for them to run.

[crash-2024-02-27_15.26.22-client.txt](https://github.com/GenerationsMod/Generations-Core/files/14425980/crash-2024-02-27_15.26.22-client.txt)
[latest.log](https://github.com/GenerationsMod/Generations-Core/files/14425982/latest.log)

Thanks!

**Comment by JT122406** [comment]
Going to close as I assume it has been resolved by current versions if not please open new issue

**Comment by Gamerbolts** [comment]
Hello again, just got the brand new version on Generations Core (3.0.0-Beta-SNAPSHOT) and still getting the same crash when trying to load into the game. Here is the updated crash log
[crash-2024-09-01_06.58.11-client.txt](https://github.com/user-attachments/files/16828786/crash-2024-09-01_06.58.11-client.txt)
Also updated my fabric to 0.16.3
